[package]
name = "decoder"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenizing = { path = "../tokenizing" }
symbols = { path = "../symbols" }
